version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: zasxcd
      POSTGRES_DB: codeigniter2
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080